### ISSUE TITLE
Model does not load

### ISSUE THREAD

**Issue by wingman-jr-addon** [Pankaj01998/Firefox-Extension-Detecting-Disturbing-Images#1]
Hello!

I took a look at helping to get your model loaded and inferring. I have attached working sources.

Please be aware that while you attempted to follow the method outlined [here](https://github.com/wingman-jr-addon/wingman_jr/) you deviated in several key ways that all ended up mattering greatly.

1. Tensorflow.js is getting loaded both as a part of the page itself and as a script in manifest.json. Please remove from your main script and load from manifest.json only.
2. Load Tensorflow.js before your other script.
3. You are loading in a content script, not a background script. This means that TF.js and your model loading occurs as part of getting injected into every page. Content scripts have different permissions than background scripts. Please do research into this area to understand other differences - performance per page load, for example, will be an issue you face immediately.
4. As a consequence of being a content script, the URL for the model needs to both be added to manifest.json as a web_accessible_resource as well as referenced in a special way using browser.runtime.url.
5. Your model is not a graph model, it is a layers model, so you need to change which API you're calling. You can potentially choose to convert it to a graph model if you are doing conversion using the model converter - you may see a speed boost. The caught exception was not very helpful, only complaining about e.versions being undefined, but that's the real issue.
6. Don't forget your image input size is different so that needs to be changed as well.

As a side note, depending on what you're trying to do with the model, I might recommend loading your model as a background script to avoid reloading on every page. You could then in theory have the content script send messages to the background script. Note the Wingman Jr. plugin takes the approach of filtering images on the way in before they load into the page as an alternative solution to this issue.

Good luck!

[borderify.js.txt](https://github.com/Pankaj01998/Firefox-Extension-Detecting-Disturbing-Images/files/3900576/borderify.js.txt)
[manifest.json.txt](https://github.com/Pankaj01998/Firefox-Extension-Detecting-Disturbing-Images/files/3900577/manifest.json.txt)

**Comment by wingman-jr-addon** [comment]
@Pankaj01998 Did you get a chance to see if this is working now?

**Comment by Pankaj01998** [comment]
> @Pankaj01998 Did you get a chance to see if this is working now?

Yes, it's working now. But how did you get the pixel matrix of images on website which is then used for prediction?

**Comment by Pankaj01998** [comment]
> @Pankaj01998 Did you get a chance to see if this is working now?

wingman-jr-addon it's working now. Thanks for your support. But how are you filtering images on the way in before they load into the page? Like how are you selecting images before loading and predicting
using the model?

**Comment by wingman-jr-addon** [comment]
Via `browser.webRequest.filterResponseData`. See [the repo here](https://github.com/wingman-jr-addon/wingman_jr/blob/master/background.js) for more details. It's not too hard, but if you're trying to do largely the same thing you may find it useful as a reference (yay forking?). Also, beware of data URL's if you use that approach.

**Comment by wingman-jr-addon** [comment]
@Pankaj01998 Any further questions? Or can we close this out?

**Comment by Pankaj01998** [comment]
@wingman-jr-addon 
0

In the below code I have imported my machine learning model through function model_startup(). model_startup() is working fine. But after that, I am getting into function blockk(), through this function I am trying to select all images on website by document.getElementsByTagName('img') and do prediction through that image with the help of an imported model. But my problem is that my second function is not selecting all images on website and selecting only some number of starting images and after prediction on that some number of images it get stopped.

I am new to javascript and trying to implement it as a firefox extension. Please help me in this problem
```
console.log('STARTING UP')

const MODEL_PATH = 'mdl/model.json'
const IMAGE_SIZE = 64;

let model;
async function model_startup() 
{

    console.log('Launching TF.js!');
    tf.ENV.set('WEBGL_PACK',false);
    await tf.ready();
    console.log('TensorflowJS backend is: '+tf.getBackend());
    let url = browser.runtime.getURL(MODEL_PATH);
    console.log('Loading model... '+url);

    try
    {
        model = await tf.loadLayersModel(url);
    }
    catch(e)
    {
        console.log('Failed to load model! '+e);
    }
    console.log('Model: ' + model);

    console.log('Warming up...');
    let dummy_data = tf.zeros([1, IMAGE_SIZE, IMAGE_SIZE, 3]);
    // dummy_data.print();  
    let warmup_result = model.predict(dummy_data);


    console.log("finding type : $$$$$$$$ " + typeof warmup_result)
    warmup_result.print();
    warmup_result.dispose();
    console.log('Ready to go!');
    // blockk();
};
model_startup().then(blockk);

function blockk() {
        const x = document.getElementsByTagName('img');
        console.log("wn ############################## " + x.length);

        let inferenceCanvas = document.createElement('canvas');
        inferenceCanvas.width = 64;
        inferenceCanvas.height = 64;
        let inferenceCtx = inferenceCanvas.getContext('2d', { alpha: false});
        inferenceCtx.imageSmoothingEnabled = true;

        for(var i = 0; i < x.length; i++)
        {
            console.log('pixel kmvsl lsvn');    

            let img = x[i];

            inferenceCtx.drawImage(img, 0, 0, img.width, img.height, 0, 0, 64, 64);
            const rightSizeImageData = inferenceCtx.getImageData(0, 0, 64, 64); //write promise. It may work.

            const rightSizeImageDataTF = tf.browser.fromPixels(rightSizeImageData);
            const floatImg = rightSizeImageDataTF.toFloat();
            console.log('predicting...');
            let scaled = floatImg.div(tf.scalar(255));
            let batched = tf.stack([scaled]);

            let result = model.predict(batched);
            const val = result.dataSync()[0];
            console.log(val);

            if (val > 0.4) 
            {

                console.log("blocking" + i);    
                let h = img.height
                let w = img.width
                pth = img.src
                x[i].setAttribute("src", "https://indianonlineseller.com/wp-content/uploads/2017/05/blocked-listing.png");
                // x[i].setAttribute("onclick", ` this.src = '${pth}' `);


                x[i].setAttribute("data-src", "https://indianonlineseller.com/wp-content/uploads/2017/05/blocked-listing.png");
                x[i].height = h;
                x[i].width = w;

                console.log('blocked');

            }
            console.log("co @@@@@@@@@@@@@@@@@@@@@@@@@@@ " + x.length)
        }
};
```

**Comment by wingman-jr-addon** [comment]
Well, could be lots of things. Couple things to check out:

1. Looks like you haven't wrapped prediction in a `tf.tidy` block. That's important so that the tensors get cleaned up. See [this line](https://github.com/wingman-jr-addon/wingman_jr/blob/master/background.js#L220)
2. Not sure your web pages but are you watching for DOM mutations etc? This might cause you to catch some images but not all.

You might be interested in [this plugin by Purify.ai as well](https://github.com/purify-ai/geacc-crx) - good luck!

**Comment by Pankaj01998** [comment]
@wingman-jr-addon 

1) Earlier I added that ```tf.tidy``` but it was working fine without that so I didn't add it.
2) I want to catch all images on webpage for prediction and then block them depending on predicted values. So please help me how can I catch all images on webpage.

Thanks in advance

**Comment by wingman-jr-addon** [comment]
Well, did you get a chance to look at the [MutationObserver API](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)? Fortunately it looks like someone has asked a similar question [over on StackOverflow](https://stackoverflow.com/questions/52444784/detect-all-images-with-javascript-in-an-html-page) - that looks like a really great place to start! When you've tried that approach, why don't you post your experiences here?

**Comment by Pankaj01998** [comment]
@wingman-jr-addon 
The line in my code which is causing problem is
``` const rightSizeImageData = inferenceCtx.getImageData(0, 0, 64, 64);```
If I remove this code and other code related to this and I run it then my code is able to select all the images on webpage. Can you tell me why this may be happening?

**Comment by Pankaj01998** [comment]
@wingman-jr-addon 

Are you able to find what is problem with that line?

**Comment by wingman-jr-addon** [comment]
Not immediately, no - but I might have a couple ideas mixed in with two general suggestions.

First, can you describe more technically what is occurring when it is not "selecting all the images on the webpage"? Specifically, does the call to get the images fail in some way - does the array x have the right items in it? Or is it that the loop fails to execute fully, and if so, is there an exception thrown? One notable difference with doing it on the webpage rather than on the network streams is that you are now needing to consider things like, "Is the document actually loaded?" (I don't see code currently listening to that event handler) and ultimately "How do I detect dynamically produced image elements?" 
Second, can you post your modified code and/or commit it with a link? I can think of more than one way to remove the line in questions and I still don't know if you have, for example, potentially run into issues with not using `tf.tidy`. I also can't run it to check as it stands. As a side note, being on a webpage as a content script may also put heavier restrictions on cross-origin images if that's something you need to be concerned about. See [here](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image#Security_and_tainted_canvases) for more details if you're not familiar.

**Comment by Pankaj01998** [comment]
@wingman-jr-addon 

Thank you so much for your help. With your help, I was able to find out the problem in my code which was due to security error. I have updated my new code which is running properly both on firefox and chrome. But currently, I am running in one issue that my model after some number of prediction is predicting same value for all rest of images.

Possible reasons may be  model is getting the same image matrix again and again for prediction


I have attached below screenshot. The blue values in console are predicted values.

![s1](https://user-images.githubusercontent.com/38392993/76708689-d648da80-671e-11ea-9a95-d9ddc50f6ea1.png)

Can you tell me why this may be happening?

**Comment by wingman-jr-addon** [comment]
Good! I'm glad to hear you got it working. Don't forget to take a peek at the mutation observer. Since you got your main problem fixed, I'm going to close this for now.
